version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: kotlin-app
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    privileged: true
    networks:
      - container-link
    env_file:
      - ../.env

  web:
    image: node:22
    container_name: web
    volumes:
      - ../web:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    networks:
      - container-link

  api:
    image: eclipse-temurin:21-jdk
    container_name: api
    volumes:
      - ../api:/app
    working_dir: /app
    command: ./gradlew bootRun
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - db
      - wiremock
    networks:
      - container-link

  db:
    image: postgres:17.5-bookworm
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - container-link

  flyway:
    image: flyway/flyway:11.9
    container_name: flyway
    depends_on:
      - db
    volumes:
      - ../flyway/sql:/flyway/sql
      - ../flyway/conf:/flyway/conf
    command: -configFiles=/flyway/conf/flyway.conf migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - container-link

  wiremock:
    image: wiremock/wiremock:3.13.0-1
    container_name: wiremock
    ports:
      - "8082:8080"
    volumes:
      - ../wiremock/__files:/home/wiremock/__files
      - ../wiremock/mappings:/home/wiremock/mappings
    networks:
      - container-link

networks:
  container-link:
    name: dev.internal
    driver: bridge

volumes:
  postgres-data:
